trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.20'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: 'provisioning/vault-auto-unseal'
    backendServiceAWS: 'Insight connection'
    backendAWSBucketName: 'amtrust-tf-state'
    backendAWSKey: 'pipelines/vault/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: aws
    command: apply
    workingDirectory: 'provisioning/vault-auto-unseal'
    commandOptions: >
      -var vpc_id=vpc-7465fa0e
    environmentServiceNameAWS: 'Insight connection'
